### ISSUE TITLE
abreloadproxy

### ISSUE THREAD

**Issue by dyanakiev** [AuthMe/AuthMeBungee#19]
Reload is not working..
> => abreloadproxy [18:34:19 INFO]: An internal error occurred whilst executing this command, please check the console log for details.
> [18:34:19 WARN]: Error in dispatching command
java.lang.NullPointerException: null
at fr.xephi.authmebungee.commands.BungeeReloadCommand.execute(BungeeReloadCommand.java:22) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:168) ~[proxy.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:115) ~[proxy.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
at io.github.waterfallmc.waterfall.console.WaterfallConsole.lambda$runCommand$0(WaterfallConsole.java:43) ~[proxy.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by sgdc3** [comment]
Thank you
