### ISSUE TITLE
Exception encountered when loading plugin: AuthMeBungee

### ISSUE THREAD

**Issue by o0Julia0o** [AuthMe/AuthMeBungee#24]
getting this at bungee-proxy #1310 starting authmebungee #2.0.2:

```
20:47:51 [WARNUNG] Exception encountered when loading plugin: AuthMeBungee
while scanning a quoted scalar
 in 'reader', line 27, column 21:
    unloggedUserServer: '
                        ^
found unexpected end of stream
 in 'reader', line 27, column 22:

    ^

    at fr.xephi.authmebungee.libs.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarSpaces(ScannerImpl.java:1933)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1847)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1029)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.scanner.ScannerImpl.fetchSingle(ScannerImpl.java:1004)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:392)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
    at fr.xephi.authmebungee.libs.yaml.snakeyaml.Yaml.load(Yaml.java:452)
    at fr.xephi.authmebungee.libs.jalu.configme.resource.YamlFileReader.reload(YamlFileReader.java:116)
    at fr.xephi.authmebungee.libs.jalu.configme.resource.YamlFileReader.<init>(YamlFileReader.java:42)
    at fr.xephi.authmebungee.libs.jalu.configme.resource.YamlFileResource.<init>(YamlFileResource.java:44)
    at fr.xephi.authmebungee.config.SettingsProvider.get(SettingsProvider.java:38)
    at fr.xephi.authmebungee.config.SettingsProvider.get(SettingsProvider.java:16)
    at fr.xephi.authmebungee.libs.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
    at fr.xephi.authmebungee.libs.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
    at fr.xephi.authmebungee.libs.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
    at fr.xephi.authmebungee.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
    at fr.xephi.authmebungee.AuthMeBungee.onEnable(AuthMeBungee.java:38)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by sgdc3** [comment]
please post your config, it is invalid

**Comment by o0Julia0o** [comment]
Thank you. I changed:
unloggedUserServer: '
to
unloggedUserServer: ''
-> now it´s working.
