### ISSUE TITLE
Errore java last build : 2170

### ISSUE THREAD

**Issue by Guest1131** [AuthMe/AuthMeBungee#33]
Hi, there,

Using spigot 1.12.2

I have updated authme to the last build: 2170, and no longer appears the login screen, and appears this error in java in the console: 

 at fr.xephi.authme.libs.com.google.common.cache.LocalCache.get(LocalCache.java:3952) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964) ~[?:?]
        at fr.xephi.authme.datasource.CacheDataSource.getAuth(CacheDataSource.java:97) ~[?:?]
        at fr.xephi.authme.datasource.CacheDataSource.isAuthAvailable(CacheDataSource.java:81) ~[?:?]
        at fr.xephi.authme.service.TeleportationService.teleportNewPlayerToFirstSpawn(TeleportationService.java:112) ~[?:?]
        at fr.xephi.authme.listener.PlayerListener.onPlayerJoin(PlayerListener.java:248) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
        ... 16 more
[07:52:59 WARN]: [AuthMe] Plugin AuthMe v5.5.0-SNAPSHOT-b2170 generated an exception while executing task 52
java.lang.NoClassDefFoundError: fr/xephi/authme/libs/com/google/common/util/concurrent/SettableFuture
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3471) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3475) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2133) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache.get(LocalCache.java:3952) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958) ~[?:?]
        at fr.xephi.authme.libs.com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964) ~[?:?]
        at fr.xephi.authme.datasource.CacheDataSource.getAuth(CacheDataSource.java:97) ~[?:?]
        at fr.xephi.authme.datasource.CacheDataSource.isAuthAvailable(CacheDataSource.java:81) ~[?:?]
        at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:106) ~[?:?]
        at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:77) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-e8ded36-acbc348]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by sgdc3** [comment]
hmm yeah something has changed in the guava library, i'll take a look at it. Use the previous build in the meantime.
