### ISSUE TITLE
Exception encountered when loading plugin: AuthMeBungee

### ISSUE THREAD

**Issue by puigru** [AuthMe/AuthMeBungee#4]
When using AuthMeBungee on the latest version of Bungee I keep getting this exception in the console, the plugin itself seems to work just fine but the config is not being created.

> 14:28:35 [ADVERTENCIA] Exception encountered when loading plugin: AuthMeBungee
ch.jalu.injector.exceptions.InjectorException: Class 'class ch.jalu.configme.SettingsManager' with package 'ch.jalu.configme' is outside of the allowed packages. It must be provided explicitly or the package must be passed to the constructor.
	at ch.jalu.injector.handlers.preconstruct.PreConstructPackageValidator.process(PreConstructPackageValidator.java:35)
	at ch.jalu.injector.handlers.preconstruct.PlainPreConstructHandler.accept(PlainPreConstructHandler.java:11)
	at ch.jalu.injector.InjectorImpl.processPreConstructorHandlers(InjectorImpl.java:244)
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:157)
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51)
	at fr.xephi.authmebungee.bungeecord.AuthMeBungee.onEnable(AuthMeBungee.java:37)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by sgdc3** [comment]
@ljacqu relocation related issue?

**Comment by ljacqu** [comment]
@sgdc3 This occurs when the injector is configured with a given package and we try to instantiate a class outside of that package.

In AuthMeBungeeSpigot:
```java
injector = new InjectorBuilder().addDefaultHandlers("fr.xephi.authmebungee.spigot").create();
```

You can fix this in different ways:
a) Don't limit what package can be instantiated, i.e. `new InjectorBuilder().addDefaultHandlers("").create()`
b) Extend SettingsManager inside the fr.xephi.auhtmebungee package and use that class instead of ConfigMe's SettingsManager
c) Register the object in the injector immediately, i.e. instead of `injector.registerProvider(SettingsManager.class, SpigotSettingsProvider.class);` use `injector.register(SettingsManager.class, settingsManager)` where `settingsManager` is the object you've created beforehand

**Comment by sgdc3** [comment]
Ok, thank you, i'll fix that asap

**Comment by sgdc3** [comment]
Thank you, @XXLuigiMario i'm very busy atm, i completely forgot about that.
