### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by DoNotSpamPls** [AuthMe/AuthMeBungee#7]
```
16:48:52 [WARNING] Error enabling plugin AuthMeBungee
java.lang.ClassNotFoundException: AuthMeBungee
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

I feel like it's because of [this](https://bitcoin.is-serious.business/142f8c.png) change in commit a30befa, correct me if I'm wrong

**Comment by sgdc3** [comment]
yeah, sorry, some automatic refactoring related issue... xD Missed that.
