### ISSUE TITLE
Something wrong with metrics classes. 

### ISSUE THREAD

**Issue by robbiemcleod56** [AuthMe/AuthMeBungee#78]
Pulled the repo and compiled it, and received this error. 
Using latest Waterfall #380.
Authme build: https://github.com/AuthMe/AuthMeReloaded/commit/782f226a2740ba2fdf236a0397d071c8c0da259e

[04:04:59] [main/WARN]: Exception encountered when loading plugin: AuthMeBungee
java.lang.ExceptionInInitializerError: null
	at fr.xephi.authmebungee.AuthMeBungee.onEnable(AuthMeBungee.java:60) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
Caused by: java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
	at org.bstats.bungeecord.Metrics.<clinit>(Metrics.java:43) ~[?:?]
	... 5 more

**Comment by sgdc3** [comment]
Fixed in the latest dev builds
